// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MediationUIClient is the client API for MediationUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediationUIClient interface {
	// ListEngineSpecs returns a list of Mediation Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (MediationUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type mediationUIClient struct {
	cc grpc.ClientConnInterface
}

func NewMediationUIClient(cc grpc.ClientConnInterface) MediationUIClient {
	return &mediationUIClient{cc}
}

func (c *mediationUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (MediationUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MediationUI_ServiceDesc.Streams[0], "/v1.MediationUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &mediationUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MediationUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type mediationUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *mediationUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mediationUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.MediationUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediationUIServer is the server API for MediationUI service.
// All implementations must embed UnimplementedMediationUIServer
// for forward compatibility
type MediationUIServer interface {
	// ListEngineSpecs returns a list of Mediation Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, MediationUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedMediationUIServer()
}

// UnimplementedMediationUIServer must be embedded to have forward compatible implementations.
type UnimplementedMediationUIServer struct {
}

func (UnimplementedMediationUIServer) ListEngineSpecs(*ListEngineSpecsRequest, MediationUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedMediationUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedMediationUIServer) mustEmbedUnimplementedMediationUIServer() {}

// UnsafeMediationUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediationUIServer will
// result in compilation errors.
type UnsafeMediationUIServer interface {
	mustEmbedUnimplementedMediationUIServer()
}

func RegisterMediationUIServer(s grpc.ServiceRegistrar, srv MediationUIServer) {
	s.RegisterService(&MediationUI_ServiceDesc, srv)
}

func _MediationUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MediationUIServer).ListEngineSpecs(m, &mediationUIListEngineSpecsServer{stream})
}

type MediationUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type mediationUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *mediationUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MediationUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediationUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MediationUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediationUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediationUI_ServiceDesc is the grpc.ServiceDesc for MediationUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediationUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MediationUI",
	HandlerType: (*MediationUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _MediationUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _MediationUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mediation-ui.proto",
}
